command=/home/robin/.config/i3/scripts/$BLOCK_NAME

[focused window]
command=xtitle -s
interval=persist

[song]
#command=mpc -h 192.168.178.50 -f "%title%"  | head -n 1
label=
interval=1

[load_average]
interval=1
label=

[disk]
interval=1
label=

[volume]
label=
interval=1

[iface]
instance=wlo1
interval=10
label=

[bandwidth]
#instance=eth0
interval=1

[wifi]
instance=wlo1
interval=10
label=

[battery]
label=BAT
label=⚡
#instance=1
interval=30

[date]
#command=date '+%b %d %H:%M'
interval=1
label=
