-- Generated by nwg-displays on 2026-05-19 at 21:58:05. Do not edit manually.

hl.monitor({
    output = "HDMI-A-2",
    mode = "3840x2160@60.0",
    position = "6000x675",
    scale = 1.0
})
hl.monitor({
    output = "DP-4",
    mode = "3840x2160@60.0",
    position = "0x0",
    scale = 1.0,
    transform = 1
})
hl.monitor({
    output = "DP-5",
    mode = "3840x2160@60.0",
    position = "2160x675",
    scale = 1.0
})
