#!/usr/bin/env bash
set -euo pipefail

# Generate rEFInd assets from a Matugen-rendered color JSON (used as a post_hook).
# Usage: refind-matugen.sh /path/to/refind-colors.json
# The JSON must contain hex strings at:
#   .primary, .secondary, .surface_container_lowest, .surface_dim

colors_json="${1:-}"

if [[ -z "${colors_json}" ]]; then
  echo "Usage: $0 /path/to/refind-colors.json" >&2
  exit 1
fi

for cmd in jq convert; do
  if ! command -v "${cmd}" >/dev/null 2>&1; then
    echo "Missing dependency: ${cmd}" >&2
    exit 1
  fi
done

if [[ ! -f "${colors_json}" ]]; then
  echo "Color file not found: ${colors_json}" >&2
  exit 1
fi

refind_dir="/boot/efi/EFI/BOOT"
theme_dir="${refind_dir}/refind-theme-matugen"

# If we can't write to the ESP, re-exec via sudo (interactive prompt if needed).
if [[ "${REFIND_MATUGEN_ESCALATED:-0}" != "1" && ! -w "${theme_dir}" ]]; then
  exec sudo REFIND_MATUGEN_ESCALATED=1 PATH="${PATH}" "$0" "$colors_json"
fi

mkdir -p "${theme_dir}"

primary="$(jq -r '.primary' "${colors_json}")"
bg_lowest="$(jq -r '.surface_container_lowest' "${colors_json}")"
bg_dim="$(jq -r '.surface_dim' "${colors_json}")"

img_bin="convert"
if command -v magick >/dev/null 2>&1; then
  img_bin="magick convert"
fi

for val in "${primary}" "${bg_lowest}" "${bg_dim}"; do
  if [[ -z "${val}" || "${val}" == "null" ]]; then
    echo "Missing expected color values in ${colors_json}" >&2
    exit 1
  fi
done

# Banner: soft gradient between two background shades to avoid banding on boot screens.
${img_bin} -size 1920x1080 "gradient:${bg_lowest}-${bg_dim}" "${theme_dir}/banner.png"
# Selection: flat fill; rEFInd applies its own overlay on hover.
${img_bin} -size 256x96 "xc:${primary}" "${theme_dir}/selection_dark-big.png"
${img_bin} -size 144x48 "xc:${primary}" "${theme_dir}/selection_dark-small.png"

cat >"${theme_dir}/theme.conf" <<'EOF'
# Auto-generated by refind-matugen.sh
icons_dir refind-theme-regular/icons/128-48
big_icon_size 128
small_icon_size 48
banner refind-theme-matugen/banner.png
selection_big refind-theme-matugen/selection_dark-big.png
selection_small refind-theme-matugen/selection_dark-small.png
font refind-theme-regular/fonts/source-code-pro-extralight-14.png
EOF

echo "rEFInd Matugen theme updated at ${theme_dir}"
